export type CategoryPair = {
  left: string;
  right: string;
};

export const categoryPairs: CategoryPair[] = [
  { left: 'Bad NFL K', right: 'Good NFL K' },
  { left: 'Good NFL K', right: 'Bad NFL K' },
  { left: 'Bad NFL RB', right: 'Good NFL RB' },
  { left: 'Good NFL RB', right: 'Bad NFL RB' },
  { left: 'Bad NFL WR', right: 'Good NFL WR' },
  { left: 'Good NFL WR', right: 'Bad NFL WR' },
  { left: 'Bad NFL QB', right: 'Good NFL QB' },
  { left: 'Good NFL QB', right: 'Bad NFL QB' },
  { left: 'Bad NFL TE', right: 'Good NFL TE' },
  { left: 'Good NFL TE', right: 'Bad NFL TE' },
  { left: 'Bad NFL DP', right: 'Good NFL DP' },
  { left: 'Good NFL DP', right: 'Bad NFL DP' },
  { left: 'Bad NFL Team', right: 'Good NFL Team' },
  { left: 'Good NFL Team', right: 'Bad NFL Team' },
  { left: 'NFL Contender', right: 'NFL Pretender' },
  { left: 'NFL Pretender', right: 'NFL Contender' },
  { left: 'Bad NBA PG', right: 'Good NBA PG' },
  { left: 'Good NBA PG', right: 'Bad NBA PG' },
  { left: 'Bad NBA SG', right: 'Good NBA SG' },
  { left: 'Good NBA SG', right: 'Bad NBA SG' },
  { left: 'Bad NBA SF', right: 'Good NBA SF' },
  { left: 'Good NBA SF', right: 'Bad NBA SF' },
  { left: 'Bad NBA PF', right: 'Good NBA PF' },
  { left: 'Good NBA PF', right: 'Bad NBA PF' },
  { left: 'Bad NBA C', right: 'Good NBA C' },
  { left: 'Good NBA C', right: 'Bad NBA C' },
  { left: 'Bad NBA Team', right: 'Good NBA Team' },
  { left: 'Good NBA Team', right: 'Bad NBA Team' },
  { left: 'NBA Contender', right: 'NBA Pretender' },
  { left: 'NBA Pretender', right: 'NBA Contender' },
  { left: 'Bad MLB Pitcher', right: 'Good MLB Pitcher' },
  { left: 'Good MLB Pitcher', right: 'Bad MLB Pitcher' },
  { left: 'Bad MLB Hitter', right: 'Good MLB Hitter' },
  { left: 'Good MLB Hitter', right: 'Bad MLB Hitter' },
  { left: 'Bad MLB Team', right: 'Good MLB Team' },
  { left: 'Good MLB Team', right: 'Bad MLB Team' },
  { left: 'Good MLB Fielder', right: 'Bad MLB Fielder' },
  { left: 'Bad MLB Fielder', right: 'Good MLB Fielder' },
  { left: 'MLB Contender', right: 'MLB Pretender' },
  { left: 'MLB Pretender', right: 'MLB Contender' },
  { left: 'NHL Pretender', right: 'NHL Contender' },
  { left: 'NHL Contender', right: 'NHL Pretender' },
  { left: 'Good NHL Forward', right: 'Bad NHL Forward' },
  { left: 'Bad NHL Forward', right: 'Good NHL Forward' },
  { left: 'Good NHL Defenseman', right: 'Bad NHL Defenseman' },
  { left: 'Bad NHL Defenseman', right: 'Good NHL Defenseman' },
  { left: 'Good NHL Goalie', right: 'Bad NHL Goalie' },
  { left: 'Bad NHL Goalie', right: 'Good NHL Goalie' },
  { left: 'Good NHL Team', right: 'Bad NHL Team' },
  { left: 'Bad NHL Team', right: 'Good NHL Team' },
  { left: 'Strong Marvel Superhero', right: 'Weak Marvel Superhero' },
  { left: 'Weak Marvel Superhero', right: 'Strong Marvel Superhero' },
  { left: 'Good Marvel Superhero', right: 'Bad Marvel Superhero' },
  { left: 'Bad Marvel Superhero', right: 'Good Marvel Superhero' },
  { left: 'Good DC Superhero', right: 'Bad DC Superhero' },
  { left: 'Bad DC Superhero', right: 'Good DC Superhero' },
  { left: 'Strong DC Superhero', right: 'Weak DC Superhero' },
  { left: 'Weak DC Superhero', right: 'Strong DC Superhero' },
  { left: 'Good DC Villain', right: 'Bad DC Villain' },
  { left: 'Bad DC Villain', right: 'Good DC Villain' },
  { left: 'Good Movie', right: 'Bad Movie' },
  { left: 'Bad Movie', right: 'Good Movie' },
  { left: 'Interesting Movie', right: 'Boring Movie' },
  { left: 'Boring Movie', right: 'Interesting Movie' },
  { left: 'Good Book', right: 'Bad Book' },
  { left: 'Bad Book', right: 'Good Book' },
  { left: 'Bad Song', right: 'Good Song' },
  { left: 'Good Song', right: 'Bad Song' },
  { left: 'Cold', right: 'Hot' },
  { left: 'Quiet', right: 'Loud' },
  { left: 'Fancy', right: 'Poor' },
  { left: 'Cheap', right: 'Expensive' },
  { left: 'Easy', right: 'Hard' },
  { left: 'Boring', right: 'Exciting' },
  { left: 'Ugly', right: 'Beautiful' },
  { left: 'Small', right: 'Large' },
  { left: 'Slow', right: 'Fast' },
  { left: 'Weak', right: 'Strong' },
  { left: 'Sad', right: 'Happy' },
  { left: 'Dry', right: 'Wet' },
  { left: 'Light', right: 'Heavy' },
  { left: 'Soft', right: 'Hard' },
  { left: 'Rough', right: 'Smooth' },
  { left: 'Dull', right: 'Sharp' },
  { left: 'Old', right: 'New' },
  { left: 'Common', right: 'Rare' },
  { left: 'Safe', right: 'Dangerous' },
  { left: 'Clean', right: 'Dirty' },
  { left: 'Short', right: 'Tall' },
  { left: 'Thin', right: 'Thick' },
  { left: 'Empty', right: 'Full' },
  { left: 'Open', right: 'Closed' },
  { left: 'Loose', right: 'Tight' },
  { left: 'Wide', right: 'Narrow' },
  { left: 'Shallow', right: 'Deep' },
  { left: 'Low', right: 'High' },
  { left: 'Near', right: 'Far' },
  { left: 'Early', right: 'Late' },
  { left: 'Young', right: 'Old' },
  { left: 'Poor', right: 'Rich' },
  { left: 'Weak', right: 'Powerful' },
  { left: 'Simple', right: 'Complex' },
  { left: 'Calm', right: 'Chaotic' },
  { left: 'Gentle', right: 'Aggressive' },
  { left: 'Friendly', right: 'Hostile' },
  { left: 'Honest', right: 'Dishonest' },
  { left: 'Brave', right: 'Cowardly' },
  { left: 'Wise', right: 'Foolish' },
  { left: 'Healthy', right: 'Unhealthy' },
  { left: 'Fresh', right: 'Stale' },
  { left: 'Sweet', right: 'Sour' },
  { left: 'Smooth', right: 'Bumpy' },
  { left: 'Bright', right: 'Dark' },
  { left: 'Clear', right: 'Cloudy' },
  { left: 'Solid', right: 'Liquid' },
  { left: 'Stable', right: 'Unstable' },
  { left: 'Organized', right: 'Messy' },
  { left: 'Ordered', right: 'Random' },
];

