export type CategoryPair = {
  left: string;
  right: string;
};

export const categoryPairs: CategoryPair[] = [
  { left: 'Bad NFL kicker', right: 'Good NFL kicker' },
  { left: 'Cold', right: 'Hot' },
  { left: 'Quiet', right: 'Loud' },
  { left: 'Cheap', right: 'Expensive' },
  { left: 'Easy', right: 'Hard' },
  { left: 'Boring', right: 'Exciting' },
  { left: 'Ugly', right: 'Beautiful' },
  { left: 'Small', right: 'Large' },
  { left: 'Slow', right: 'Fast' },
  { left: 'Weak', right: 'Strong' },
  { left: 'Sad', right: 'Happy' },
  { left: 'Dry', right: 'Wet' },
  { left: 'Light', right: 'Heavy' },
  { left: 'Soft', right: 'Hard' },
  { left: 'Rough', right: 'Smooth' },
  { left: 'Dull', right: 'Sharp' },
  { left: 'Old', right: 'New' },
  { left: 'Common', right: 'Rare' },
  { left: 'Safe', right: 'Dangerous' },
  { left: 'Clean', right: 'Dirty' },
  { left: 'Short', right: 'Tall' },
  { left: 'Thin', right: 'Thick' },
  { left: 'Empty', right: 'Full' },
  { left: 'Open', right: 'Closed' },
  { left: 'Loose', right: 'Tight' },
  { left: 'Wide', right: 'Narrow' },
  { left: 'Shallow', right: 'Deep' },
  { left: 'Low', right: 'High' },
  { left: 'Near', right: 'Far' },
  { left: 'Early', right: 'Late' },
  { left: 'Young', right: 'Old' },
  { left: 'Poor', right: 'Rich' },
  { left: 'Weak', right: 'Powerful' },
  { left: 'Simple', right: 'Complex' },
  { left: 'Calm', right: 'Chaotic' },
  { left: 'Gentle', right: 'Aggressive' },
  { left: 'Friendly', right: 'Hostile' },
  { left: 'Honest', right: 'Dishonest' },
  { left: 'Brave', right: 'Cowardly' },
  { left: 'Wise', right: 'Foolish' },
  { left: 'Healthy', right: 'Unhealthy' },
  { left: 'Fresh', right: 'Stale' },
  { left: 'Sweet', right: 'Sour' },
  { left: 'Smooth', right: 'Bumpy' },
  { left: 'Bright', right: 'Dark' },
  { left: 'Clear', right: 'Cloudy' },
  { left: 'Solid', right: 'Liquid' },
  { left: 'Stable', right: 'Unstable' },
  { left: 'Organized', right: 'Messy' },
  { left: 'Ordered', right: 'Random' },
];

